name: Run Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  gotest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Unshallow
        run: git fetch --prune --unshallow
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.18
      
      - name: Build
        run: go build -v ./..

      - name: Test
        run: go test -v ./..
